---
- hosts: all
  name: Install MySQL database
  become: yes
  gather_facts: false

  pre_tasks:
      - name: Install Python 2.x
        raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
        register: output
        changed_when: output.stdout != ""
      - name: Gathering Facts
        setup:

  tasks:
      - name: Install DataBase
        apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
        with_items:
            - mysql-server-5.7
            - mysql-client-5.7
            - mysql-common
            - python-mysqldb

      - name: Start the MySQL service
        service: 
            name: mysql 
            state: started
            enabled: true

      - name: Removes all anonymous user accounts
        mysql_user:
            name: ''
            host_all: yes
            state: absent

      - name: Removes test database
        mysql_db:
            name: test
            state: absent

      - name: Create new database
        mysql_db:
            name: '{{ db_name }}'
            state: present

      - name: Create new database user
        mysql_user:
            name: '{{ db_user }}'
            host: '{{ db_remote_user_hosts }}'
            password: '{{ db_pass }}'
            priv: '{{ db_name }}.*:ALL,GRANT'
            state: present

      - name: Copy global cnf file
        template:
            src: templates/mysql.cnf.j2
            dest: /etc/mysql/my.cnf
        register: gcnf

      - name: Restart MySQL server
        become: true
        service: name=mysql state=restarted
        when: gcnf.changed

      - name: Check that user can connect to database
        mysql_db:
            login_user: '{{ db_user }}'
            login_password: '{{ db_pass }}'
            login_host: '{{ db_host }}'
            login_port: '{{ db_port }}'
            name: '{{ db_name }}'
            state: present
